feat: 그룹공부방0 페이지 api 구현
HeyyoProject/heyyo-back pull request #23
Opened 2023-08-27 15:03 UTC by wan2daaa

## ✔ 지라 이슈 번호
HEY-57

## 📒 작업 내용
- 서브모듈 업데이트 
- 버그 수정 ( 서브모듈, uri 오류)
- S3 서비스 로직 구현 
- 그룹공부방0 페이지 api로직 구현 ( s3는 일단 넘어가고 추후 작업예정 및 이런친구들 어때요 부분도 추후 작업예상)

## 📢 리뷰어에게 하고 싶은 말
ex) 어디어디를 중점적으로 봐주세요 ...

## 📌 PR 전 체크 사항
- [x] base 브랜치가 **develop** 브랜치로 되어있나요?
- [x] PR title에 PR Type을 표시해 두었나요? (feat:, fix:, refact: ...)
- [x] test가 모두 통과 되었나요?

2023-08-27 17:46 UTC, 5tr1ker requested changes

2023-08-27 17:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/group/study/service/GroupStudyService.java
> +        return groupStudyTags;
움 이러면 N * 2 의 시간 복잡도인데 쿼리로 Tag 데이터만 가져오는 건 어떤가용.
데이터 양이 적다면 괜찮을 거 같긴해요

2023-08-27 17:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/util/s3/service/S3Service.java
> +                .body(urlResource);
그 프론트엔드에서 S3 스토리지를 바로 다운로드할 수 있습니다!

https://velog.io/@kados22/react-s3-%ED%8C%8C%EC%9D%BC-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C-%EB%B2%84%ED%8A%BC-%EA%B5%AC%ED%98%84

2023-08-27 17:51 UTC, 5tr1ker submitted a review, later dismissed
머지하기 전에 요청 사항 한번 꼭 봐주세요!

2023-08-28 02:43 UTC, wan2daaa commented on src/main/java/com/team/heyyo/util/s3/service/S3Service.java
> +                .body(urlResource);
아 이건 그 자료실목록에서 다운로드 버튼 누를때 해당 api 누르면 바로 다운로드 하게 할려고 했습니다 ㅎ

2023-08-28 02:43 UTC, wan2daaa commented on src/main/java/com/team/heyyo/group/study/service/GroupStudyService.java
> +        return groupStudyTags;
상진씨 말이 맞는것같아요 ㅎ 수정하겠습니다! 👍 냉철합니다

2023-08-28 05:03 UTC, 5tr1ker approved these changes
고생하셨습니다!

2023-08-28 10:14 UTC, merged