feat: JWT 구현, OAuth2 구현 및 Security Configuration 마무리
HeyyoProject/heyyo-back pull request #4
Opened 2023-07-20 16:14 UTC by wan2daaa

## JWT
accessToken 과 refreshToken 으로 나눠서 구현하였고,
refreshToken은 db 에 저장하고,
accessToken 은 필터(TokenAuthenticationFilter.java)에서
검증 되고 처리되고,

refreshToken은 POST /api/tokens 로 재발급 가능하고, 검증되고 accessToken을 리턴하게 구현

## OAuth2
Oauth2 로그인 성공 후
refreshToken 과 accessToken을 전달할 때
->
refreshToken은 cookie로
accessToken 은 url 파라미터로 전달하게 구현

로그아웃은 클라이언트 쪽에서 삭제하면 되어서 따로 처리하지 않았습니다.

# 체크해주셨으면 하는 부분 
Outh2 쪽이 조금 부족한 것같아서 그쪽 위주로 체크해 주시면 감사하곘습니다!

2023-07-21 05:21 UTC, 5tr1ker requested changes

2023-07-21 05:21 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/config/SpringSecurityConfig.java
>      public PasswordEncoder passwordEncoder() {
RefreshToken은 서버에서 보관되기 때문에 클라이언트가 삭제하지 못하며 ,  서버에서 삭제해 주어야 합니다.

.logout()
.logoutUrl("/logout")
.deleteCookies("refreshToken")
를 사용해서 제거할 수 있습니다. ( /logout url로 들어가야해용

2023-07-21 05:21 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/config/SpringSecurityConfig.java
>      public PasswordEncoder passwordEncoder() {
/api/tokens 도 좋지만 , 만료된 즉시 AccessToken 을 반환해서 api 통신 횟수를 줄일 수 있는 방법이 있습니다!

2023-07-21 05:21 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
BCryptPasswordEncoder 는 Configuration 에서 스프링 컨테이너에 보관되어있기 때문에 Dependency Injection 으로 주입할 수 있지 않을까요

2023-07-21 05:21 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +    }
예외가 발생했을 때 이것을 담을 Exception Handler가 없는거같습니다! 그리구 메세지도 직관적으로 변경되면 좋을꺼같아요!

2023-07-21 05:21 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/config/jwt/controller/TokenApiController.java
> +    }
201은 새로운 자원이 생성되었을 때 사용되는데 AccessToken 은 자원 생성과는 거리가 있어보이는데 어떻게 생각하시나용

그리구 따로 변수로 빼지 않고 메서드를 바로 호출할 수 있을 꺼 같아요,
ResponseEntity.ok().body(tokenService.createNewAccessToken(request));

2023-07-21 05:30 UTC, 5tr1ker submitted a review, later dismissed

2023-07-22 09:31 UTC, wan2daaa commented on src/main/java/com/team/heyyo/config/SpringSecurityConfig.java
>      public PasswordEncoder passwordEncoder() {
추가했습니다 감사합니다!

2023-07-22 09:32 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
맞습니다,,, 스프링 공부의 중요성

2023-07-22 09:32 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +    }
일단 임시로 만들어 놓았는데 그럼 구현하도록하겠습니다!

2023-07-22 09:35 UTC, wan2daaa commented on src/main/java/com/team/heyyo/config/jwt/controller/TokenApiController.java
> +    }
음 제 생각은 POST 요청으로 요청을 했으니까 이에 따른 자원 생성이 문맥상 맞다고 저는 생각하는데 그럼 혹시 어떤 걸로 수정하는게 좋을까요?? 

너무 인라인을 하게 되면 조금 가독성이 떨어져 보일까봐 구분하긴했는데 그럼 말씀하신것처럼 수정해보겠습니다!

2023-07-23 03:32 UTC, 5tr1ker approved these changes
고생하셨숩니다!

2023-07-23 07:55 UTC, merged