feat: 로그인, 회원가입 로직 구현
HeyyoProject/heyyo-back pull request #8
Opened 2023-08-02 16:47 UTC by wan2daaa

## ✔ 지라 이슈 번호
HEY-13

## 📒 작업 내용
- 로그인 코드 구현 
로그인 도 oauth2 와 동일하게 accessToken은 header에 담고, refreshToken은 cookie에 담게 설계 
- 회원가입 코드 구현 
- ControllerAdvice에 예상 못한 Exception을 잡는 코드 추가 

## 📢 리뷰어에게 하고 싶은 말
- 컨트롤러 코드 위주로 봐주시면 감사하겠습니다!  ( + 테스트 코드)

## 📌 PR 전 체크 사항
- [x] base 브랜치가 **develop** 브랜치로 되어있나요?
- [x] PR title에 PR Type을 표시해 두었나요? (feat:, fix:, refact: ...)
- [x] test가 모두 통과 되었나요?

2023-08-03 15:46 UTC, 5tr1ker requested changes

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/auth/jwt/support/TokenAuthenticationFilter.java
>                      }
쿠키들을 탐색하면서 refreshToken을 찾는거같은데 다음과 같이 작성하면 더 깔끔할 꺼 같아요 참고만해주세용

if (cookies != null) {
            accessToken = Arrays.stream(cookies)
                    .filter(c -> c.getName().equals("accessToken")).findFirst().map(Cookie::getValue)
                    .orElse(null);
        }

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/controller/UserController.java
> +    }
컨트롤러 계층에 비즈니스 로직이 존재하는데 서비스 계층으로 옮길 수 있을까용.

/login method 는 보통 post를 하더라구요. 그 이유는 get에는 body를 넣을 수 없어서 파라미터로 넘겨줘야 하는데 이는 보안상 취약해서 그렇더라구요.

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/dto/UserLoginResponse.java
> +
혹시 code 에는 상태 코드값으로 넣는걸 통일할까욥

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +        }
String result = optionalValue.orElseGet(() -> {
            return "Generated Default Value";
        });

이런 식으로 값을 리턴할 수 있을 꺼 같은데 한번 확인해주실 수 있나용

2023-08-03 15:46 UTC, 5tr1ker commented on src/test/java/com/team/heyyo/user/controller/UserControllerTest.java
> +}
Controller 테스트에 실패하는 테스트가 없는거같아용..

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/controller/UserController.java
> +    }
혹시 ok 응답 코드는 200 인데 200 코드를 넣은 이유가 궁금합니당

2023-08-03 15:46 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +        }
그러면 자연스레 밑에 .get() 코드가 제거되어서 코드가 더 깨끗해질 꺼 같아요!

2023-08-04 03:20 UTC, wan2daaa commented on src/main/java/com/team/heyyo/auth/jwt/support/TokenAuthenticationFilter.java
>                      }
좋은것같습니다 감사합니다!

2023-08-04 03:24 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/controller/UserController.java
> +    }
다른 큰의미는 없고, 프론트쪽과 소통할 때 어떤 코드를 넘겨줄지 그런걸 안 정해서 일단 넣었는데 빼도 될것같습니다!

2023-08-04 03:30 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/controller/UserController.java
> +    }
처음 생각했을 땐 서비스의 메소드 하나의 역할을 좀 줄일려고 했는데 잘못생각한것 같아요 수정하겠습니다! 

저도 post get 이 헷갈렸는데 일단 의미적으로는 get이 맞는것같아서 그렇게 진행하였는데 post로 수정하겠습니다 :>

2023-08-04 03:42 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/dto/UserLoginResponse.java
> +
이건 제가 잘못생각한 것같아요 안넣어도될것같은데 code를 빼겠습니다!

2023-08-04 03:53 UTC, wan2daaa commented on src/main/java/com/team/heyyo/user/service/UserService.java
> +        }
덕분에 좋은 코드가 생각나서 수정했습니다 :> 감사합니다!

2023-08-04 14:34 UTC, wan2daaa commented on src/test/java/com/team/heyyo/user/controller/UserControllerTest.java
> +}
추가하였습니다! 회원가입은 이메일 검증을 하기 때문에 따로 실패케이스를 작성하지 않았습니다 :>

2023-08-05 02:52 UTC, 5tr1ker approved these changes

2023-08-05 02:52 UTC, 5tr1ker commented on src/main/resources/application.yaml
>    profiles:
이것도 민감한 정보인데 따로 private 레포지토리에 저장하지 않고 해도될까욥

2023-08-05 03:01 UTC, 5tr1ker approved these changes

2023-08-05 03:01 UTC, 5tr1ker commented on src/main/java/com/team/heyyo/user/controller/UserFindController.java
> +  }
findPasswordWithEmailAndName 메서드 안에서 위의 로직의 결과를 반환해도 되지 않을까요. 
url에 개인정보 유출되는거랑, 비즈니스 로직이 컨트롤러 계층에 있는게 좀 맘에 걸리네용..

2023-08-05 04:09 UTC, wan2daaa commented on src/main/resources/application.yaml
>    profiles:
일단 커밋하구 추후 수정하겠습니다! 지라에 올렪갰습나더!

2023-08-05 05:36 UTC, merged